// generated by cdk8s
import { ApiObject, ApiObjectMetadata, GroupVersionKind } from 'cdk8s';
import { Construct } from 'constructs';


/**
 * CloudEventSource defines how a KEDA event will be sent to event sink
 *
 * @schema CloudEventSource
 */
export class CloudEventSource extends ApiObject {
  /**
   * Returns the apiVersion and kind for "CloudEventSource"
   */
  public static readonly GVK: GroupVersionKind = {
    apiVersion: 'eventing.keda.sh/v1alpha1',
    kind: 'CloudEventSource',
  }

  /**
   * Renders a Kubernetes manifest for "CloudEventSource".
   *
   * This can be used to inline resource manifests inside other objects (e.g. as templates).
   *
   * @param props initialization props
   */
  public static manifest(props: CloudEventSourceProps): any {
    return {
      ...CloudEventSource.GVK,
      ...toJson_CloudEventSourceProps(props),
    };
  }

  /**
   * Defines a "CloudEventSource" API object
   * @param scope the scope in which to define this object
   * @param id a scope-local name for the object
   * @param props initialization props
   */
  public constructor(scope: Construct, id: string, props: CloudEventSourceProps) {
    super(scope, id, {
      ...CloudEventSource.GVK,
      ...props,
    });
  }

  /**
   * Renders the object to Kubernetes JSON.
   */
  public override toJson(): any {
    const resolved = super.toJson();

    return {
      ...CloudEventSource.GVK,
      ...toJson_CloudEventSourceProps(resolved),
    };
  }
}

/**
 * CloudEventSource defines how a KEDA event will be sent to event sink
 *
 * @schema CloudEventSource
 */
export interface CloudEventSourceProps {
  /**
   * @schema CloudEventSource#metadata
   */
  readonly metadata?: ApiObjectMetadata;

  /**
   * CloudEventSourceSpec defines the spec of CloudEventSource
   *
   * @schema CloudEventSource#spec
   */
  readonly spec: CloudEventSourceSpec;

}

/**
 * Converts an object of type 'CloudEventSourceProps' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_CloudEventSourceProps(obj: CloudEventSourceProps | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'metadata': obj.metadata,
    'spec': toJson_CloudEventSourceSpec(obj.spec),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * CloudEventSourceSpec defines the spec of CloudEventSource
 *
 * @schema CloudEventSourceSpec
 */
export interface CloudEventSourceSpec {
  /**
   * AuthenticationRef points to the TriggerAuthentication or ClusterTriggerAuthentication object that
   * is used to authenticate the scaler with the environment
   *
   * @schema CloudEventSourceSpec#authenticationRef
   */
  readonly authenticationRef?: CloudEventSourceSpecAuthenticationRef;

  /**
   * @schema CloudEventSourceSpec#clusterName
   */
  readonly clusterName?: string;

  /**
   * Destination defines the various ways to emit events
   *
   * @schema CloudEventSourceSpec#destination
   */
  readonly destination: CloudEventSourceSpecDestination;

  /**
   * EventSubscription defines filters for events
   *
   * @schema CloudEventSourceSpec#eventSubscription
   */
  readonly eventSubscription?: CloudEventSourceSpecEventSubscription;

}

/**
 * Converts an object of type 'CloudEventSourceSpec' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_CloudEventSourceSpec(obj: CloudEventSourceSpec | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'authenticationRef': toJson_CloudEventSourceSpecAuthenticationRef(obj.authenticationRef),
    'clusterName': obj.clusterName,
    'destination': toJson_CloudEventSourceSpecDestination(obj.destination),
    'eventSubscription': toJson_CloudEventSourceSpecEventSubscription(obj.eventSubscription),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * AuthenticationRef points to the TriggerAuthentication or ClusterTriggerAuthentication object that
 * is used to authenticate the scaler with the environment
 *
 * @schema CloudEventSourceSpecAuthenticationRef
 */
export interface CloudEventSourceSpecAuthenticationRef {
  /**
   * Kind of the resource being referred to. Defaults to TriggerAuthentication.
   *
   * @default TriggerAuthentication.
   * @schema CloudEventSourceSpecAuthenticationRef#kind
   */
  readonly kind?: string;

  /**
   * @schema CloudEventSourceSpecAuthenticationRef#name
   */
  readonly name: string;

}

/**
 * Converts an object of type 'CloudEventSourceSpecAuthenticationRef' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_CloudEventSourceSpecAuthenticationRef(obj: CloudEventSourceSpecAuthenticationRef | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'kind': obj.kind,
    'name': obj.name,
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * Destination defines the various ways to emit events
 *
 * @schema CloudEventSourceSpecDestination
 */
export interface CloudEventSourceSpecDestination {
  /**
   * @schema CloudEventSourceSpecDestination#azureEventGridTopic
   */
  readonly azureEventGridTopic?: CloudEventSourceSpecDestinationAzureEventGridTopic;

  /**
   * @schema CloudEventSourceSpecDestination#http
   */
  readonly http?: CloudEventSourceSpecDestinationHttp;

}

/**
 * Converts an object of type 'CloudEventSourceSpecDestination' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_CloudEventSourceSpecDestination(obj: CloudEventSourceSpecDestination | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'azureEventGridTopic': toJson_CloudEventSourceSpecDestinationAzureEventGridTopic(obj.azureEventGridTopic),
    'http': toJson_CloudEventSourceSpecDestinationHttp(obj.http),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * EventSubscription defines filters for events
 *
 * @schema CloudEventSourceSpecEventSubscription
 */
export interface CloudEventSourceSpecEventSubscription {
  /**
   * @schema CloudEventSourceSpecEventSubscription#excludedEventTypes
   */
  readonly excludedEventTypes?: CloudEventSourceSpecEventSubscriptionExcludedEventTypes[];

  /**
   * @schema CloudEventSourceSpecEventSubscription#includedEventTypes
   */
  readonly includedEventTypes?: CloudEventSourceSpecEventSubscriptionIncludedEventTypes[];

}

/**
 * Converts an object of type 'CloudEventSourceSpecEventSubscription' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_CloudEventSourceSpecEventSubscription(obj: CloudEventSourceSpecEventSubscription | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'excludedEventTypes': obj.excludedEventTypes?.map(y => y),
    'includedEventTypes': obj.includedEventTypes?.map(y => y),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * @schema CloudEventSourceSpecDestinationAzureEventGridTopic
 */
export interface CloudEventSourceSpecDestinationAzureEventGridTopic {
  /**
   * @schema CloudEventSourceSpecDestinationAzureEventGridTopic#endpoint
   */
  readonly endpoint: string;

}

/**
 * Converts an object of type 'CloudEventSourceSpecDestinationAzureEventGridTopic' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_CloudEventSourceSpecDestinationAzureEventGridTopic(obj: CloudEventSourceSpecDestinationAzureEventGridTopic | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'endpoint': obj.endpoint,
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * @schema CloudEventSourceSpecDestinationHttp
 */
export interface CloudEventSourceSpecDestinationHttp {
  /**
   * @schema CloudEventSourceSpecDestinationHttp#uri
   */
  readonly uri: string;

}

/**
 * Converts an object of type 'CloudEventSourceSpecDestinationHttp' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_CloudEventSourceSpecDestinationHttp(obj: CloudEventSourceSpecDestinationHttp | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'uri': obj.uri,
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * @schema CloudEventSourceSpecEventSubscriptionExcludedEventTypes
 */
export enum CloudEventSourceSpecEventSubscriptionExcludedEventTypes {
  /** keda.scaledobject.ready.v1 */
  KEDA_PERIOD_SCALEDOBJECT_PERIOD_READY_PERIOD_V1 = "keda.scaledobject.ready.v1",
  /** keda.scaledobject.failed.v1 */
  KEDA_PERIOD_SCALEDOBJECT_PERIOD_FAILED_PERIOD_V1 = "keda.scaledobject.failed.v1",
  /** keda.scaledobject.removed.v1 */
  KEDA_PERIOD_SCALEDOBJECT_PERIOD_REMOVED_PERIOD_V1 = "keda.scaledobject.removed.v1",
  /** keda.scaledjob.ready.v1 */
  KEDA_PERIOD_SCALEDJOB_PERIOD_READY_PERIOD_V1 = "keda.scaledjob.ready.v1",
  /** keda.scaledjob.failed.v1 */
  KEDA_PERIOD_SCALEDJOB_PERIOD_FAILED_PERIOD_V1 = "keda.scaledjob.failed.v1",
  /** keda.scaledjob.removed.v1 */
  KEDA_PERIOD_SCALEDJOB_PERIOD_REMOVED_PERIOD_V1 = "keda.scaledjob.removed.v1",
  /** keda.authentication.triggerauthentication.created.v1 */
  KEDA_PERIOD_AUTHENTICATION_PERIOD_TRIGGERAUTHENTICATION_PERIOD_CREATED_PERIOD_V1 = "keda.authentication.triggerauthentication.created.v1",
  /** keda.authentication.triggerauthentication.updated.v1 */
  KEDA_PERIOD_AUTHENTICATION_PERIOD_TRIGGERAUTHENTICATION_PERIOD_UPDATED_PERIOD_V1 = "keda.authentication.triggerauthentication.updated.v1",
  /** keda.authentication.triggerauthentication.removed.v1 */
  KEDA_PERIOD_AUTHENTICATION_PERIOD_TRIGGERAUTHENTICATION_PERIOD_REMOVED_PERIOD_V1 = "keda.authentication.triggerauthentication.removed.v1",
  /** keda.authentication.clustertriggerauthentication.created.v1 */
  KEDA_PERIOD_AUTHENTICATION_PERIOD_CLUSTERTRIGGERAUTHENTICATION_PERIOD_CREATED_PERIOD_V1 = "keda.authentication.clustertriggerauthentication.created.v1",
  /** keda.authentication.clustertriggerauthentication.updated.v1 */
  KEDA_PERIOD_AUTHENTICATION_PERIOD_CLUSTERTRIGGERAUTHENTICATION_PERIOD_UPDATED_PERIOD_V1 = "keda.authentication.clustertriggerauthentication.updated.v1",
  /** keda.authentication.clustertriggerauthentication.removed.v1 */
  KEDA_PERIOD_AUTHENTICATION_PERIOD_CLUSTERTRIGGERAUTHENTICATION_PERIOD_REMOVED_PERIOD_V1 = "keda.authentication.clustertriggerauthentication.removed.v1",
}

/**
 * @schema CloudEventSourceSpecEventSubscriptionIncludedEventTypes
 */
export enum CloudEventSourceSpecEventSubscriptionIncludedEventTypes {
  /** keda.scaledobject.ready.v1 */
  KEDA_PERIOD_SCALEDOBJECT_PERIOD_READY_PERIOD_V1 = "keda.scaledobject.ready.v1",
  /** keda.scaledobject.failed.v1 */
  KEDA_PERIOD_SCALEDOBJECT_PERIOD_FAILED_PERIOD_V1 = "keda.scaledobject.failed.v1",
  /** keda.scaledobject.removed.v1 */
  KEDA_PERIOD_SCALEDOBJECT_PERIOD_REMOVED_PERIOD_V1 = "keda.scaledobject.removed.v1",
  /** keda.scaledjob.ready.v1 */
  KEDA_PERIOD_SCALEDJOB_PERIOD_READY_PERIOD_V1 = "keda.scaledjob.ready.v1",
  /** keda.scaledjob.failed.v1 */
  KEDA_PERIOD_SCALEDJOB_PERIOD_FAILED_PERIOD_V1 = "keda.scaledjob.failed.v1",
  /** keda.scaledjob.removed.v1 */
  KEDA_PERIOD_SCALEDJOB_PERIOD_REMOVED_PERIOD_V1 = "keda.scaledjob.removed.v1",
  /** keda.authentication.triggerauthentication.created.v1 */
  KEDA_PERIOD_AUTHENTICATION_PERIOD_TRIGGERAUTHENTICATION_PERIOD_CREATED_PERIOD_V1 = "keda.authentication.triggerauthentication.created.v1",
  /** keda.authentication.triggerauthentication.updated.v1 */
  KEDA_PERIOD_AUTHENTICATION_PERIOD_TRIGGERAUTHENTICATION_PERIOD_UPDATED_PERIOD_V1 = "keda.authentication.triggerauthentication.updated.v1",
  /** keda.authentication.triggerauthentication.removed.v1 */
  KEDA_PERIOD_AUTHENTICATION_PERIOD_TRIGGERAUTHENTICATION_PERIOD_REMOVED_PERIOD_V1 = "keda.authentication.triggerauthentication.removed.v1",
  /** keda.authentication.clustertriggerauthentication.created.v1 */
  KEDA_PERIOD_AUTHENTICATION_PERIOD_CLUSTERTRIGGERAUTHENTICATION_PERIOD_CREATED_PERIOD_V1 = "keda.authentication.clustertriggerauthentication.created.v1",
  /** keda.authentication.clustertriggerauthentication.updated.v1 */
  KEDA_PERIOD_AUTHENTICATION_PERIOD_CLUSTERTRIGGERAUTHENTICATION_PERIOD_UPDATED_PERIOD_V1 = "keda.authentication.clustertriggerauthentication.updated.v1",
  /** keda.authentication.clustertriggerauthentication.removed.v1 */
  KEDA_PERIOD_AUTHENTICATION_PERIOD_CLUSTERTRIGGERAUTHENTICATION_PERIOD_REMOVED_PERIOD_V1 = "keda.authentication.clustertriggerauthentication.removed.v1",
}


/**
 *
 *
 * @schema ClusterCloudEventSource
 */
export class ClusterCloudEventSource extends ApiObject {
  /**
   * Returns the apiVersion and kind for "ClusterCloudEventSource"
   */
  public static readonly GVK: GroupVersionKind = {
    apiVersion: 'eventing.keda.sh/v1alpha1',
    kind: 'ClusterCloudEventSource',
  }

  /**
   * Renders a Kubernetes manifest for "ClusterCloudEventSource".
   *
   * This can be used to inline resource manifests inside other objects (e.g. as templates).
   *
   * @param props initialization props
   */
  public static manifest(props: ClusterCloudEventSourceProps): any {
    return {
      ...ClusterCloudEventSource.GVK,
      ...toJson_ClusterCloudEventSourceProps(props),
    };
  }

  /**
   * Defines a "ClusterCloudEventSource" API object
   * @param scope the scope in which to define this object
   * @param id a scope-local name for the object
   * @param props initialization props
   */
  public constructor(scope: Construct, id: string, props: ClusterCloudEventSourceProps) {
    super(scope, id, {
      ...ClusterCloudEventSource.GVK,
      ...props,
    });
  }

  /**
   * Renders the object to Kubernetes JSON.
   */
  public override toJson(): any {
    const resolved = super.toJson();

    return {
      ...ClusterCloudEventSource.GVK,
      ...toJson_ClusterCloudEventSourceProps(resolved),
    };
  }
}

/**
 * @schema ClusterCloudEventSource
 */
export interface ClusterCloudEventSourceProps {
  /**
   * @schema ClusterCloudEventSource#metadata
   */
  readonly metadata?: ApiObjectMetadata;

  /**
   * CloudEventSourceSpec defines the spec of CloudEventSource
   *
   * @schema ClusterCloudEventSource#spec
   */
  readonly spec: ClusterCloudEventSourceSpec;

}

/**
 * Converts an object of type 'ClusterCloudEventSourceProps' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_ClusterCloudEventSourceProps(obj: ClusterCloudEventSourceProps | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'metadata': obj.metadata,
    'spec': toJson_ClusterCloudEventSourceSpec(obj.spec),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * CloudEventSourceSpec defines the spec of CloudEventSource
 *
 * @schema ClusterCloudEventSourceSpec
 */
export interface ClusterCloudEventSourceSpec {
  /**
   * AuthenticationRef points to the TriggerAuthentication or ClusterTriggerAuthentication object that
   * is used to authenticate the scaler with the environment
   *
   * @schema ClusterCloudEventSourceSpec#authenticationRef
   */
  readonly authenticationRef?: ClusterCloudEventSourceSpecAuthenticationRef;

  /**
   * @schema ClusterCloudEventSourceSpec#clusterName
   */
  readonly clusterName?: string;

  /**
   * Destination defines the various ways to emit events
   *
   * @schema ClusterCloudEventSourceSpec#destination
   */
  readonly destination: ClusterCloudEventSourceSpecDestination;

  /**
   * EventSubscription defines filters for events
   *
   * @schema ClusterCloudEventSourceSpec#eventSubscription
   */
  readonly eventSubscription?: ClusterCloudEventSourceSpecEventSubscription;

}

/**
 * Converts an object of type 'ClusterCloudEventSourceSpec' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_ClusterCloudEventSourceSpec(obj: ClusterCloudEventSourceSpec | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'authenticationRef': toJson_ClusterCloudEventSourceSpecAuthenticationRef(obj.authenticationRef),
    'clusterName': obj.clusterName,
    'destination': toJson_ClusterCloudEventSourceSpecDestination(obj.destination),
    'eventSubscription': toJson_ClusterCloudEventSourceSpecEventSubscription(obj.eventSubscription),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * AuthenticationRef points to the TriggerAuthentication or ClusterTriggerAuthentication object that
 * is used to authenticate the scaler with the environment
 *
 * @schema ClusterCloudEventSourceSpecAuthenticationRef
 */
export interface ClusterCloudEventSourceSpecAuthenticationRef {
  /**
   * Kind of the resource being referred to. Defaults to TriggerAuthentication.
   *
   * @default TriggerAuthentication.
   * @schema ClusterCloudEventSourceSpecAuthenticationRef#kind
   */
  readonly kind?: string;

  /**
   * @schema ClusterCloudEventSourceSpecAuthenticationRef#name
   */
  readonly name: string;

}

/**
 * Converts an object of type 'ClusterCloudEventSourceSpecAuthenticationRef' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_ClusterCloudEventSourceSpecAuthenticationRef(obj: ClusterCloudEventSourceSpecAuthenticationRef | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'kind': obj.kind,
    'name': obj.name,
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * Destination defines the various ways to emit events
 *
 * @schema ClusterCloudEventSourceSpecDestination
 */
export interface ClusterCloudEventSourceSpecDestination {
  /**
   * @schema ClusterCloudEventSourceSpecDestination#azureEventGridTopic
   */
  readonly azureEventGridTopic?: ClusterCloudEventSourceSpecDestinationAzureEventGridTopic;

  /**
   * @schema ClusterCloudEventSourceSpecDestination#http
   */
  readonly http?: ClusterCloudEventSourceSpecDestinationHttp;

}

/**
 * Converts an object of type 'ClusterCloudEventSourceSpecDestination' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_ClusterCloudEventSourceSpecDestination(obj: ClusterCloudEventSourceSpecDestination | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'azureEventGridTopic': toJson_ClusterCloudEventSourceSpecDestinationAzureEventGridTopic(obj.azureEventGridTopic),
    'http': toJson_ClusterCloudEventSourceSpecDestinationHttp(obj.http),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * EventSubscription defines filters for events
 *
 * @schema ClusterCloudEventSourceSpecEventSubscription
 */
export interface ClusterCloudEventSourceSpecEventSubscription {
  /**
   * @schema ClusterCloudEventSourceSpecEventSubscription#excludedEventTypes
   */
  readonly excludedEventTypes?: ClusterCloudEventSourceSpecEventSubscriptionExcludedEventTypes[];

  /**
   * @schema ClusterCloudEventSourceSpecEventSubscription#includedEventTypes
   */
  readonly includedEventTypes?: ClusterCloudEventSourceSpecEventSubscriptionIncludedEventTypes[];

}

/**
 * Converts an object of type 'ClusterCloudEventSourceSpecEventSubscription' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_ClusterCloudEventSourceSpecEventSubscription(obj: ClusterCloudEventSourceSpecEventSubscription | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'excludedEventTypes': obj.excludedEventTypes?.map(y => y),
    'includedEventTypes': obj.includedEventTypes?.map(y => y),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * @schema ClusterCloudEventSourceSpecDestinationAzureEventGridTopic
 */
export interface ClusterCloudEventSourceSpecDestinationAzureEventGridTopic {
  /**
   * @schema ClusterCloudEventSourceSpecDestinationAzureEventGridTopic#endpoint
   */
  readonly endpoint: string;

}

/**
 * Converts an object of type 'ClusterCloudEventSourceSpecDestinationAzureEventGridTopic' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_ClusterCloudEventSourceSpecDestinationAzureEventGridTopic(obj: ClusterCloudEventSourceSpecDestinationAzureEventGridTopic | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'endpoint': obj.endpoint,
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * @schema ClusterCloudEventSourceSpecDestinationHttp
 */
export interface ClusterCloudEventSourceSpecDestinationHttp {
  /**
   * @schema ClusterCloudEventSourceSpecDestinationHttp#uri
   */
  readonly uri: string;

}

/**
 * Converts an object of type 'ClusterCloudEventSourceSpecDestinationHttp' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_ClusterCloudEventSourceSpecDestinationHttp(obj: ClusterCloudEventSourceSpecDestinationHttp | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'uri': obj.uri,
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * @schema ClusterCloudEventSourceSpecEventSubscriptionExcludedEventTypes
 */
export enum ClusterCloudEventSourceSpecEventSubscriptionExcludedEventTypes {
  /** keda.scaledobject.ready.v1 */
  KEDA_PERIOD_SCALEDOBJECT_PERIOD_READY_PERIOD_V1 = "keda.scaledobject.ready.v1",
  /** keda.scaledobject.failed.v1 */
  KEDA_PERIOD_SCALEDOBJECT_PERIOD_FAILED_PERIOD_V1 = "keda.scaledobject.failed.v1",
  /** keda.scaledobject.removed.v1 */
  KEDA_PERIOD_SCALEDOBJECT_PERIOD_REMOVED_PERIOD_V1 = "keda.scaledobject.removed.v1",
  /** keda.scaledjob.ready.v1 */
  KEDA_PERIOD_SCALEDJOB_PERIOD_READY_PERIOD_V1 = "keda.scaledjob.ready.v1",
  /** keda.scaledjob.failed.v1 */
  KEDA_PERIOD_SCALEDJOB_PERIOD_FAILED_PERIOD_V1 = "keda.scaledjob.failed.v1",
  /** keda.scaledjob.removed.v1 */
  KEDA_PERIOD_SCALEDJOB_PERIOD_REMOVED_PERIOD_V1 = "keda.scaledjob.removed.v1",
  /** keda.authentication.triggerauthentication.created.v1 */
  KEDA_PERIOD_AUTHENTICATION_PERIOD_TRIGGERAUTHENTICATION_PERIOD_CREATED_PERIOD_V1 = "keda.authentication.triggerauthentication.created.v1",
  /** keda.authentication.triggerauthentication.updated.v1 */
  KEDA_PERIOD_AUTHENTICATION_PERIOD_TRIGGERAUTHENTICATION_PERIOD_UPDATED_PERIOD_V1 = "keda.authentication.triggerauthentication.updated.v1",
  /** keda.authentication.triggerauthentication.removed.v1 */
  KEDA_PERIOD_AUTHENTICATION_PERIOD_TRIGGERAUTHENTICATION_PERIOD_REMOVED_PERIOD_V1 = "keda.authentication.triggerauthentication.removed.v1",
  /** keda.authentication.clustertriggerauthentication.created.v1 */
  KEDA_PERIOD_AUTHENTICATION_PERIOD_CLUSTERTRIGGERAUTHENTICATION_PERIOD_CREATED_PERIOD_V1 = "keda.authentication.clustertriggerauthentication.created.v1",
  /** keda.authentication.clustertriggerauthentication.updated.v1 */
  KEDA_PERIOD_AUTHENTICATION_PERIOD_CLUSTERTRIGGERAUTHENTICATION_PERIOD_UPDATED_PERIOD_V1 = "keda.authentication.clustertriggerauthentication.updated.v1",
  /** keda.authentication.clustertriggerauthentication.removed.v1 */
  KEDA_PERIOD_AUTHENTICATION_PERIOD_CLUSTERTRIGGERAUTHENTICATION_PERIOD_REMOVED_PERIOD_V1 = "keda.authentication.clustertriggerauthentication.removed.v1",
}

/**
 * @schema ClusterCloudEventSourceSpecEventSubscriptionIncludedEventTypes
 */
export enum ClusterCloudEventSourceSpecEventSubscriptionIncludedEventTypes {
  /** keda.scaledobject.ready.v1 */
  KEDA_PERIOD_SCALEDOBJECT_PERIOD_READY_PERIOD_V1 = "keda.scaledobject.ready.v1",
  /** keda.scaledobject.failed.v1 */
  KEDA_PERIOD_SCALEDOBJECT_PERIOD_FAILED_PERIOD_V1 = "keda.scaledobject.failed.v1",
  /** keda.scaledobject.removed.v1 */
  KEDA_PERIOD_SCALEDOBJECT_PERIOD_REMOVED_PERIOD_V1 = "keda.scaledobject.removed.v1",
  /** keda.scaledjob.ready.v1 */
  KEDA_PERIOD_SCALEDJOB_PERIOD_READY_PERIOD_V1 = "keda.scaledjob.ready.v1",
  /** keda.scaledjob.failed.v1 */
  KEDA_PERIOD_SCALEDJOB_PERIOD_FAILED_PERIOD_V1 = "keda.scaledjob.failed.v1",
  /** keda.scaledjob.removed.v1 */
  KEDA_PERIOD_SCALEDJOB_PERIOD_REMOVED_PERIOD_V1 = "keda.scaledjob.removed.v1",
  /** keda.authentication.triggerauthentication.created.v1 */
  KEDA_PERIOD_AUTHENTICATION_PERIOD_TRIGGERAUTHENTICATION_PERIOD_CREATED_PERIOD_V1 = "keda.authentication.triggerauthentication.created.v1",
  /** keda.authentication.triggerauthentication.updated.v1 */
  KEDA_PERIOD_AUTHENTICATION_PERIOD_TRIGGERAUTHENTICATION_PERIOD_UPDATED_PERIOD_V1 = "keda.authentication.triggerauthentication.updated.v1",
  /** keda.authentication.triggerauthentication.removed.v1 */
  KEDA_PERIOD_AUTHENTICATION_PERIOD_TRIGGERAUTHENTICATION_PERIOD_REMOVED_PERIOD_V1 = "keda.authentication.triggerauthentication.removed.v1",
  /** keda.authentication.clustertriggerauthentication.created.v1 */
  KEDA_PERIOD_AUTHENTICATION_PERIOD_CLUSTERTRIGGERAUTHENTICATION_PERIOD_CREATED_PERIOD_V1 = "keda.authentication.clustertriggerauthentication.created.v1",
  /** keda.authentication.clustertriggerauthentication.updated.v1 */
  KEDA_PERIOD_AUTHENTICATION_PERIOD_CLUSTERTRIGGERAUTHENTICATION_PERIOD_UPDATED_PERIOD_V1 = "keda.authentication.clustertriggerauthentication.updated.v1",
  /** keda.authentication.clustertriggerauthentication.removed.v1 */
  KEDA_PERIOD_AUTHENTICATION_PERIOD_CLUSTERTRIGGERAUTHENTICATION_PERIOD_REMOVED_PERIOD_V1 = "keda.authentication.clustertriggerauthentication.removed.v1",
}

