// generated by cdk8s
import { ApiObject, ApiObjectMetadata, GroupVersionKind } from 'cdk8s';
import { Construct } from 'constructs';


/**
 * ImageUpdateAutomation is the Schema for the imageupdateautomations API
 *
 * @schema ImageUpdateAutomation
 */
export class ImageUpdateAutomation extends ApiObject {
  /**
   * Returns the apiVersion and kind for "ImageUpdateAutomation"
   */
  public static readonly GVK: GroupVersionKind = {
    apiVersion: 'image.toolkit.fluxcd.io/v1beta1',
    kind: 'ImageUpdateAutomation',
  }

  /**
   * Renders a Kubernetes manifest for "ImageUpdateAutomation".
   *
   * This can be used to inline resource manifests inside other objects (e.g. as templates).
   *
   * @param props initialization props
   */
  public static manifest(props: ImageUpdateAutomationProps = {}): any {
    return {
      ...ImageUpdateAutomation.GVK,
      ...toJson_ImageUpdateAutomationProps(props),
    };
  }

  /**
   * Defines a "ImageUpdateAutomation" API object
   * @param scope the scope in which to define this object
   * @param id a scope-local name for the object
   * @param props initialization props
   */
  public constructor(scope: Construct, id: string, props: ImageUpdateAutomationProps = {}) {
    super(scope, id, {
      ...ImageUpdateAutomation.GVK,
      ...props,
    });
  }

  /**
   * Renders the object to Kubernetes JSON.
   */
  public override toJson(): any {
    const resolved = super.toJson();

    return {
      ...ImageUpdateAutomation.GVK,
      ...toJson_ImageUpdateAutomationProps(resolved),
    };
  }
}

/**
 * ImageUpdateAutomation is the Schema for the imageupdateautomations API
 *
 * @schema ImageUpdateAutomation
 */
export interface ImageUpdateAutomationProps {
  /**
   * @schema ImageUpdateAutomation#metadata
   */
  readonly metadata?: ApiObjectMetadata;

  /**
   * ImageUpdateAutomationSpec defines the desired state of ImageUpdateAutomation
   *
   * @schema ImageUpdateAutomation#spec
   */
  readonly spec?: ImageUpdateAutomationSpec;

}

/**
 * Converts an object of type 'ImageUpdateAutomationProps' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_ImageUpdateAutomationProps(obj: ImageUpdateAutomationProps | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'metadata': obj.metadata,
    'spec': toJson_ImageUpdateAutomationSpec(obj.spec),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * ImageUpdateAutomationSpec defines the desired state of ImageUpdateAutomation
 *
 * @schema ImageUpdateAutomationSpec
 */
export interface ImageUpdateAutomationSpec {
  /**
   * GitSpec contains all the git-specific definitions. This is
   * technically optional, but in practice mandatory until there are
   * other kinds of source allowed.
   *
   * @schema ImageUpdateAutomationSpec#git
   */
  readonly git?: ImageUpdateAutomationSpecGit;

  /**
   * Interval gives an lower bound for how often the automation
   * run should be attempted.
   *
   * @schema ImageUpdateAutomationSpec#interval
   */
  readonly interval: string;

  /**
   * SourceRef refers to the resource giving access details
   * to a git repository.
   *
   * @schema ImageUpdateAutomationSpec#sourceRef
   */
  readonly sourceRef: ImageUpdateAutomationSpecSourceRef;

  /**
   * Suspend tells the controller to not run this automation, until
   * it is unset (or set to false). Defaults to false.
   *
   * @default false.
   * @schema ImageUpdateAutomationSpec#suspend
   */
  readonly suspend?: boolean;

  /**
   * Update gives the specification for how to update the files in
   * the repository. This can be left empty, to use the default
   * value.
   *
   * @schema ImageUpdateAutomationSpec#update
   */
  readonly update?: ImageUpdateAutomationSpecUpdate;

}

/**
 * Converts an object of type 'ImageUpdateAutomationSpec' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_ImageUpdateAutomationSpec(obj: ImageUpdateAutomationSpec | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'git': toJson_ImageUpdateAutomationSpecGit(obj.git),
    'interval': obj.interval,
    'sourceRef': toJson_ImageUpdateAutomationSpecSourceRef(obj.sourceRef),
    'suspend': obj.suspend,
    'update': toJson_ImageUpdateAutomationSpecUpdate(obj.update),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * GitSpec contains all the git-specific definitions. This is
 * technically optional, but in practice mandatory until there are
 * other kinds of source allowed.
 *
 * @schema ImageUpdateAutomationSpecGit
 */
export interface ImageUpdateAutomationSpecGit {
  /**
   * Checkout gives the parameters for cloning the git repository,
   * ready to make changes. If not present, the `spec.ref` field from the
   * referenced `GitRepository` or its default will be used.
   *
   * @schema ImageUpdateAutomationSpecGit#checkout
   */
  readonly checkout?: ImageUpdateAutomationSpecGitCheckout;

  /**
   * Commit specifies how to commit to the git repository.
   *
   * @schema ImageUpdateAutomationSpecGit#commit
   */
  readonly commit: ImageUpdateAutomationSpecGitCommit;

  /**
   * Push specifies how and where to push commits made by the
   * automation. If missing, commits are pushed (back) to
   * `.spec.checkout.branch` or its default.
   *
   * @schema ImageUpdateAutomationSpecGit#push
   */
  readonly push?: ImageUpdateAutomationSpecGitPush;

}

/**
 * Converts an object of type 'ImageUpdateAutomationSpecGit' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_ImageUpdateAutomationSpecGit(obj: ImageUpdateAutomationSpecGit | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'checkout': toJson_ImageUpdateAutomationSpecGitCheckout(obj.checkout),
    'commit': toJson_ImageUpdateAutomationSpecGitCommit(obj.commit),
    'push': toJson_ImageUpdateAutomationSpecGitPush(obj.push),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * SourceRef refers to the resource giving access details
 * to a git repository.
 *
 * @schema ImageUpdateAutomationSpecSourceRef
 */
export interface ImageUpdateAutomationSpecSourceRef {
  /**
   * API version of the referent.
   *
   * @schema ImageUpdateAutomationSpecSourceRef#apiVersion
   */
  readonly apiVersion?: string;

  /**
   * Kind of the referent.
   *
   * @schema ImageUpdateAutomationSpecSourceRef#kind
   */
  readonly kind: ImageUpdateAutomationSpecSourceRefKind;

  /**
   * Name of the referent.
   *
   * @schema ImageUpdateAutomationSpecSourceRef#name
   */
  readonly name: string;

  /**
   * Namespace of the referent, defaults to the namespace of the Kubernetes resource object that contains the reference.
   *
   * @schema ImageUpdateAutomationSpecSourceRef#namespace
   */
  readonly namespace?: string;

}

/**
 * Converts an object of type 'ImageUpdateAutomationSpecSourceRef' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_ImageUpdateAutomationSpecSourceRef(obj: ImageUpdateAutomationSpecSourceRef | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'apiVersion': obj.apiVersion,
    'kind': obj.kind,
    'name': obj.name,
    'namespace': obj.namespace,
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * Update gives the specification for how to update the files in
 * the repository. This can be left empty, to use the default
 * value.
 *
 * @schema ImageUpdateAutomationSpecUpdate
 */
export interface ImageUpdateAutomationSpecUpdate {
  /**
   * Path to the directory containing the manifests to be updated.
   * Defaults to 'None', which translates to the root path
   * of the GitRepositoryRef.
   *
   * @default None', which translates to the root path
   * @schema ImageUpdateAutomationSpecUpdate#path
   */
  readonly path?: string;

  /**
   * Strategy names the strategy to be used.
   *
   * @schema ImageUpdateAutomationSpecUpdate#strategy
   */
  readonly strategy: ImageUpdateAutomationSpecUpdateStrategy;

}

/**
 * Converts an object of type 'ImageUpdateAutomationSpecUpdate' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_ImageUpdateAutomationSpecUpdate(obj: ImageUpdateAutomationSpecUpdate | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'path': obj.path,
    'strategy': obj.strategy,
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * Checkout gives the parameters for cloning the git repository,
 * ready to make changes. If not present, the `spec.ref` field from the
 * referenced `GitRepository` or its default will be used.
 *
 * @schema ImageUpdateAutomationSpecGitCheckout
 */
export interface ImageUpdateAutomationSpecGitCheckout {
  /**
   * Reference gives a branch, tag or commit to clone from the Git
   * repository.
   *
   * @schema ImageUpdateAutomationSpecGitCheckout#ref
   */
  readonly ref: ImageUpdateAutomationSpecGitCheckoutRef;

}

/**
 * Converts an object of type 'ImageUpdateAutomationSpecGitCheckout' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_ImageUpdateAutomationSpecGitCheckout(obj: ImageUpdateAutomationSpecGitCheckout | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'ref': toJson_ImageUpdateAutomationSpecGitCheckoutRef(obj.ref),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * Commit specifies how to commit to the git repository.
 *
 * @schema ImageUpdateAutomationSpecGitCommit
 */
export interface ImageUpdateAutomationSpecGitCommit {
  /**
   * Author gives the email and optionally the name to use as the
   * author of commits.
   *
   * @schema ImageUpdateAutomationSpecGitCommit#author
   */
  readonly author: ImageUpdateAutomationSpecGitCommitAuthor;

  /**
   * MessageTemplate provides a template for the commit message,
   * into which will be interpolated the details of the change made.
   *
   * @schema ImageUpdateAutomationSpecGitCommit#messageTemplate
   */
  readonly messageTemplate?: string;

  /**
   * SigningKey provides the option to sign commits with a GPG key
   *
   * @schema ImageUpdateAutomationSpecGitCommit#signingKey
   */
  readonly signingKey?: ImageUpdateAutomationSpecGitCommitSigningKey;

}

/**
 * Converts an object of type 'ImageUpdateAutomationSpecGitCommit' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_ImageUpdateAutomationSpecGitCommit(obj: ImageUpdateAutomationSpecGitCommit | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'author': toJson_ImageUpdateAutomationSpecGitCommitAuthor(obj.author),
    'messageTemplate': obj.messageTemplate,
    'signingKey': toJson_ImageUpdateAutomationSpecGitCommitSigningKey(obj.signingKey),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * Push specifies how and where to push commits made by the
 * automation. If missing, commits are pushed (back) to
 * `.spec.checkout.branch` or its default.
 *
 * @schema ImageUpdateAutomationSpecGitPush
 */
export interface ImageUpdateAutomationSpecGitPush {
  /**
   * Branch specifies that commits should be pushed to the branch
   * named. The branch is created using `.spec.checkout.branch` as the
   * starting point, if it doesn't already exist.
   *
   * @schema ImageUpdateAutomationSpecGitPush#branch
   */
  readonly branch?: string;

  /**
   * Options specifies the push options that are sent to the Git
   * server when performing a push operation. For details, see:
   * https://git-scm.com/docs/git-push#Documentation/git-push.txt---push-optionltoptiongt
   *
   * @schema ImageUpdateAutomationSpecGitPush#options
   */
  readonly options?: { [key: string]: string };

  /**
   * Refspec specifies the Git Refspec to use for a push operation.
   * If both Branch and Refspec are provided, then the commit is pushed
   * to the branch and also using the specified refspec.
   * For more details about Git Refspecs, see:
   * https://git-scm.com/book/en/v2/Git-Internals-The-Refspec
   *
   * @schema ImageUpdateAutomationSpecGitPush#refspec
   */
  readonly refspec?: string;

}

/**
 * Converts an object of type 'ImageUpdateAutomationSpecGitPush' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_ImageUpdateAutomationSpecGitPush(obj: ImageUpdateAutomationSpecGitPush | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'branch': obj.branch,
    'options': ((obj.options) === undefined) ? undefined : (Object.entries(obj.options).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {})),
    'refspec': obj.refspec,
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * Kind of the referent.
 *
 * @schema ImageUpdateAutomationSpecSourceRefKind
 */
export enum ImageUpdateAutomationSpecSourceRefKind {
  /** GitRepository */
  GIT_REPOSITORY = "GitRepository",
}

/**
 * Strategy names the strategy to be used.
 *
 * @schema ImageUpdateAutomationSpecUpdateStrategy
 */
export enum ImageUpdateAutomationSpecUpdateStrategy {
  /** Setters */
  SETTERS = "Setters",
}

/**
 * Reference gives a branch, tag or commit to clone from the Git
 * repository.
 *
 * @schema ImageUpdateAutomationSpecGitCheckoutRef
 */
export interface ImageUpdateAutomationSpecGitCheckoutRef {
  /**
   * Branch to check out, defaults to 'master' if no other field is defined.
   *
   * @schema ImageUpdateAutomationSpecGitCheckoutRef#branch
   */
  readonly branch?: string;

  /**
   * Commit SHA to check out, takes precedence over all reference fields.
   *
   *
   * This can be combined with Branch to shallow clone the branch, in which
   * the commit is expected to exist.
   *
   * @schema ImageUpdateAutomationSpecGitCheckoutRef#commit
   */
  readonly commit?: string;

  /**
   * Name of the reference to check out; takes precedence over Branch, Tag and SemVer.
   *
   *
   * It must be a valid Git reference: https://git-scm.com/docs/git-check-ref-format#_description
   * Examples: "refs/heads/main", "refs/tags/v0.1.0", "refs/pull/420/head", "refs/merge-requests/1/head"
   *
   * @schema ImageUpdateAutomationSpecGitCheckoutRef#name
   */
  readonly name?: string;

  /**
   * SemVer tag expression to check out, takes precedence over Tag.
   *
   * @schema ImageUpdateAutomationSpecGitCheckoutRef#semver
   */
  readonly semver?: string;

  /**
   * Tag to check out, takes precedence over Branch.
   *
   * @schema ImageUpdateAutomationSpecGitCheckoutRef#tag
   */
  readonly tag?: string;

}

/**
 * Converts an object of type 'ImageUpdateAutomationSpecGitCheckoutRef' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_ImageUpdateAutomationSpecGitCheckoutRef(obj: ImageUpdateAutomationSpecGitCheckoutRef | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'branch': obj.branch,
    'commit': obj.commit,
    'name': obj.name,
    'semver': obj.semver,
    'tag': obj.tag,
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * Author gives the email and optionally the name to use as the
 * author of commits.
 *
 * @schema ImageUpdateAutomationSpecGitCommitAuthor
 */
export interface ImageUpdateAutomationSpecGitCommitAuthor {
  /**
   * Email gives the email to provide when making a commit.
   *
   * @schema ImageUpdateAutomationSpecGitCommitAuthor#email
   */
  readonly email: string;

  /**
   * Name gives the name to provide when making a commit.
   *
   * @schema ImageUpdateAutomationSpecGitCommitAuthor#name
   */
  readonly name?: string;

}

/**
 * Converts an object of type 'ImageUpdateAutomationSpecGitCommitAuthor' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_ImageUpdateAutomationSpecGitCommitAuthor(obj: ImageUpdateAutomationSpecGitCommitAuthor | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'email': obj.email,
    'name': obj.name,
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * SigningKey provides the option to sign commits with a GPG key
 *
 * @schema ImageUpdateAutomationSpecGitCommitSigningKey
 */
export interface ImageUpdateAutomationSpecGitCommitSigningKey {
  /**
   * SecretRef holds the name to a secret that contains a 'git.asc' key
   * corresponding to the ASCII Armored file containing the GPG signing
   * keypair as the value. It must be in the same namespace as the
   * ImageUpdateAutomation.
   *
   * @schema ImageUpdateAutomationSpecGitCommitSigningKey#secretRef
   */
  readonly secretRef?: ImageUpdateAutomationSpecGitCommitSigningKeySecretRef;

}

/**
 * Converts an object of type 'ImageUpdateAutomationSpecGitCommitSigningKey' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_ImageUpdateAutomationSpecGitCommitSigningKey(obj: ImageUpdateAutomationSpecGitCommitSigningKey | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'secretRef': toJson_ImageUpdateAutomationSpecGitCommitSigningKeySecretRef(obj.secretRef),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * SecretRef holds the name to a secret that contains a 'git.asc' key
 * corresponding to the ASCII Armored file containing the GPG signing
 * keypair as the value. It must be in the same namespace as the
 * ImageUpdateAutomation.
 *
 * @schema ImageUpdateAutomationSpecGitCommitSigningKeySecretRef
 */
export interface ImageUpdateAutomationSpecGitCommitSigningKeySecretRef {
  /**
   * Name of the referent.
   *
   * @schema ImageUpdateAutomationSpecGitCommitSigningKeySecretRef#name
   */
  readonly name: string;

}

/**
 * Converts an object of type 'ImageUpdateAutomationSpecGitCommitSigningKeySecretRef' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_ImageUpdateAutomationSpecGitCommitSigningKeySecretRef(obj: ImageUpdateAutomationSpecGitCommitSigningKeySecretRef | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'name': obj.name,
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */


/**
 * ImageUpdateAutomation is the Schema for the imageupdateautomations API
 *
 * @schema ImageUpdateAutomationV1Beta2
 */
export class ImageUpdateAutomationV1Beta2 extends ApiObject {
  /**
   * Returns the apiVersion and kind for "ImageUpdateAutomationV1Beta2"
   */
  public static readonly GVK: GroupVersionKind = {
    apiVersion: 'image.toolkit.fluxcd.io/v1beta2',
    kind: 'ImageUpdateAutomation',
  }

  /**
   * Renders a Kubernetes manifest for "ImageUpdateAutomationV1Beta2".
   *
   * This can be used to inline resource manifests inside other objects (e.g. as templates).
   *
   * @param props initialization props
   */
  public static manifest(props: ImageUpdateAutomationV1Beta2Props = {}): any {
    return {
      ...ImageUpdateAutomationV1Beta2.GVK,
      ...toJson_ImageUpdateAutomationV1Beta2Props(props),
    };
  }

  /**
   * Defines a "ImageUpdateAutomationV1Beta2" API object
   * @param scope the scope in which to define this object
   * @param id a scope-local name for the object
   * @param props initialization props
   */
  public constructor(scope: Construct, id: string, props: ImageUpdateAutomationV1Beta2Props = {}) {
    super(scope, id, {
      ...ImageUpdateAutomationV1Beta2.GVK,
      ...props,
    });
  }

  /**
   * Renders the object to Kubernetes JSON.
   */
  public override toJson(): any {
    const resolved = super.toJson();

    return {
      ...ImageUpdateAutomationV1Beta2.GVK,
      ...toJson_ImageUpdateAutomationV1Beta2Props(resolved),
    };
  }
}

/**
 * ImageUpdateAutomation is the Schema for the imageupdateautomations API
 *
 * @schema ImageUpdateAutomationV1Beta2
 */
export interface ImageUpdateAutomationV1Beta2Props {
  /**
   * @schema ImageUpdateAutomationV1Beta2#metadata
   */
  readonly metadata?: ApiObjectMetadata;

  /**
   * ImageUpdateAutomationSpec defines the desired state of ImageUpdateAutomation
   *
   * @schema ImageUpdateAutomationV1Beta2#spec
   */
  readonly spec?: ImageUpdateAutomationV1Beta2Spec;

}

/**
 * Converts an object of type 'ImageUpdateAutomationV1Beta2Props' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_ImageUpdateAutomationV1Beta2Props(obj: ImageUpdateAutomationV1Beta2Props | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'metadata': obj.metadata,
    'spec': toJson_ImageUpdateAutomationV1Beta2Spec(obj.spec),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * ImageUpdateAutomationSpec defines the desired state of ImageUpdateAutomation
 *
 * @schema ImageUpdateAutomationV1Beta2Spec
 */
export interface ImageUpdateAutomationV1Beta2Spec {
  /**
   * GitSpec contains all the git-specific definitions. This is
   * technically optional, but in practice mandatory until there are
   * other kinds of source allowed.
   *
   * @schema ImageUpdateAutomationV1Beta2Spec#git
   */
  readonly git?: ImageUpdateAutomationV1Beta2SpecGit;

  /**
   * Interval gives an lower bound for how often the automation
   * run should be attempted.
   *
   * @schema ImageUpdateAutomationV1Beta2Spec#interval
   */
  readonly interval: string;

  /**
   * PolicySelector allows to filter applied policies based on labels.
   * By default includes all policies in namespace.
   *
   * @schema ImageUpdateAutomationV1Beta2Spec#policySelector
   */
  readonly policySelector?: ImageUpdateAutomationV1Beta2SpecPolicySelector;

  /**
   * SourceRef refers to the resource giving access details
   * to a git repository.
   *
   * @schema ImageUpdateAutomationV1Beta2Spec#sourceRef
   */
  readonly sourceRef: ImageUpdateAutomationV1Beta2SpecSourceRef;

  /**
   * Suspend tells the controller to not run this automation, until
   * it is unset (or set to false). Defaults to false.
   *
   * @default false.
   * @schema ImageUpdateAutomationV1Beta2Spec#suspend
   */
  readonly suspend?: boolean;

  /**
   * Update gives the specification for how to update the files in
   * the repository. This can be left empty, to use the default
   * value.
   *
   * @schema ImageUpdateAutomationV1Beta2Spec#update
   */
  readonly update?: ImageUpdateAutomationV1Beta2SpecUpdate;

}

/**
 * Converts an object of type 'ImageUpdateAutomationV1Beta2Spec' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_ImageUpdateAutomationV1Beta2Spec(obj: ImageUpdateAutomationV1Beta2Spec | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'git': toJson_ImageUpdateAutomationV1Beta2SpecGit(obj.git),
    'interval': obj.interval,
    'policySelector': toJson_ImageUpdateAutomationV1Beta2SpecPolicySelector(obj.policySelector),
    'sourceRef': toJson_ImageUpdateAutomationV1Beta2SpecSourceRef(obj.sourceRef),
    'suspend': obj.suspend,
    'update': toJson_ImageUpdateAutomationV1Beta2SpecUpdate(obj.update),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * GitSpec contains all the git-specific definitions. This is
 * technically optional, but in practice mandatory until there are
 * other kinds of source allowed.
 *
 * @schema ImageUpdateAutomationV1Beta2SpecGit
 */
export interface ImageUpdateAutomationV1Beta2SpecGit {
  /**
   * Checkout gives the parameters for cloning the git repository,
   * ready to make changes. If not present, the `spec.ref` field from the
   * referenced `GitRepository` or its default will be used.
   *
   * @schema ImageUpdateAutomationV1Beta2SpecGit#checkout
   */
  readonly checkout?: ImageUpdateAutomationV1Beta2SpecGitCheckout;

  /**
   * Commit specifies how to commit to the git repository.
   *
   * @schema ImageUpdateAutomationV1Beta2SpecGit#commit
   */
  readonly commit: ImageUpdateAutomationV1Beta2SpecGitCommit;

  /**
   * Push specifies how and where to push commits made by the
   * automation. If missing, commits are pushed (back) to
   * `.spec.checkout.branch` or its default.
   *
   * @schema ImageUpdateAutomationV1Beta2SpecGit#push
   */
  readonly push?: ImageUpdateAutomationV1Beta2SpecGitPush;

}

/**
 * Converts an object of type 'ImageUpdateAutomationV1Beta2SpecGit' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_ImageUpdateAutomationV1Beta2SpecGit(obj: ImageUpdateAutomationV1Beta2SpecGit | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'checkout': toJson_ImageUpdateAutomationV1Beta2SpecGitCheckout(obj.checkout),
    'commit': toJson_ImageUpdateAutomationV1Beta2SpecGitCommit(obj.commit),
    'push': toJson_ImageUpdateAutomationV1Beta2SpecGitPush(obj.push),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * PolicySelector allows to filter applied policies based on labels.
 * By default includes all policies in namespace.
 *
 * @schema ImageUpdateAutomationV1Beta2SpecPolicySelector
 */
export interface ImageUpdateAutomationV1Beta2SpecPolicySelector {
  /**
   * matchExpressions is a list of label selector requirements. The requirements are ANDed.
   *
   * @schema ImageUpdateAutomationV1Beta2SpecPolicySelector#matchExpressions
   */
  readonly matchExpressions?: ImageUpdateAutomationV1Beta2SpecPolicySelectorMatchExpressions[];

  /**
   * matchLabels is a map of {key,value} pairs. A single {key,value} in the matchLabels
   * map is equivalent to an element of matchExpressions, whose key field is "key", the
   * operator is "In", and the values array contains only "value". The requirements are ANDed.
   *
   * @schema ImageUpdateAutomationV1Beta2SpecPolicySelector#matchLabels
   */
  readonly matchLabels?: { [key: string]: string };

}

/**
 * Converts an object of type 'ImageUpdateAutomationV1Beta2SpecPolicySelector' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_ImageUpdateAutomationV1Beta2SpecPolicySelector(obj: ImageUpdateAutomationV1Beta2SpecPolicySelector | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'matchExpressions': obj.matchExpressions?.map(y => toJson_ImageUpdateAutomationV1Beta2SpecPolicySelectorMatchExpressions(y)),
    'matchLabels': ((obj.matchLabels) === undefined) ? undefined : (Object.entries(obj.matchLabels).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {})),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * SourceRef refers to the resource giving access details
 * to a git repository.
 *
 * @schema ImageUpdateAutomationV1Beta2SpecSourceRef
 */
export interface ImageUpdateAutomationV1Beta2SpecSourceRef {
  /**
   * API version of the referent.
   *
   * @schema ImageUpdateAutomationV1Beta2SpecSourceRef#apiVersion
   */
  readonly apiVersion?: string;

  /**
   * Kind of the referent.
   *
   * @schema ImageUpdateAutomationV1Beta2SpecSourceRef#kind
   */
  readonly kind: ImageUpdateAutomationV1Beta2SpecSourceRefKind;

  /**
   * Name of the referent.
   *
   * @schema ImageUpdateAutomationV1Beta2SpecSourceRef#name
   */
  readonly name: string;

  /**
   * Namespace of the referent, defaults to the namespace of the Kubernetes resource object that contains the reference.
   *
   * @schema ImageUpdateAutomationV1Beta2SpecSourceRef#namespace
   */
  readonly namespace?: string;

}

/**
 * Converts an object of type 'ImageUpdateAutomationV1Beta2SpecSourceRef' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_ImageUpdateAutomationV1Beta2SpecSourceRef(obj: ImageUpdateAutomationV1Beta2SpecSourceRef | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'apiVersion': obj.apiVersion,
    'kind': obj.kind,
    'name': obj.name,
    'namespace': obj.namespace,
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * Update gives the specification for how to update the files in
 * the repository. This can be left empty, to use the default
 * value.
 *
 * @schema ImageUpdateAutomationV1Beta2SpecUpdate
 */
export interface ImageUpdateAutomationV1Beta2SpecUpdate {
  /**
   * Path to the directory containing the manifests to be updated.
   * Defaults to 'None', which translates to the root path
   * of the GitRepositoryRef.
   *
   * @default None', which translates to the root path
   * @schema ImageUpdateAutomationV1Beta2SpecUpdate#path
   */
  readonly path?: string;

  /**
   * Strategy names the strategy to be used.
   *
   * @schema ImageUpdateAutomationV1Beta2SpecUpdate#strategy
   */
  readonly strategy: ImageUpdateAutomationV1Beta2SpecUpdateStrategy;

}

/**
 * Converts an object of type 'ImageUpdateAutomationV1Beta2SpecUpdate' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_ImageUpdateAutomationV1Beta2SpecUpdate(obj: ImageUpdateAutomationV1Beta2SpecUpdate | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'path': obj.path,
    'strategy': obj.strategy,
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * Checkout gives the parameters for cloning the git repository,
 * ready to make changes. If not present, the `spec.ref` field from the
 * referenced `GitRepository` or its default will be used.
 *
 * @schema ImageUpdateAutomationV1Beta2SpecGitCheckout
 */
export interface ImageUpdateAutomationV1Beta2SpecGitCheckout {
  /**
   * Reference gives a branch, tag or commit to clone from the Git
   * repository.
   *
   * @schema ImageUpdateAutomationV1Beta2SpecGitCheckout#ref
   */
  readonly ref: ImageUpdateAutomationV1Beta2SpecGitCheckoutRef;

}

/**
 * Converts an object of type 'ImageUpdateAutomationV1Beta2SpecGitCheckout' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_ImageUpdateAutomationV1Beta2SpecGitCheckout(obj: ImageUpdateAutomationV1Beta2SpecGitCheckout | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'ref': toJson_ImageUpdateAutomationV1Beta2SpecGitCheckoutRef(obj.ref),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * Commit specifies how to commit to the git repository.
 *
 * @schema ImageUpdateAutomationV1Beta2SpecGitCommit
 */
export interface ImageUpdateAutomationV1Beta2SpecGitCommit {
  /**
   * Author gives the email and optionally the name to use as the
   * author of commits.
   *
   * @schema ImageUpdateAutomationV1Beta2SpecGitCommit#author
   */
  readonly author: ImageUpdateAutomationV1Beta2SpecGitCommitAuthor;

  /**
   * MessageTemplate provides a template for the commit message,
   * into which will be interpolated the details of the change made.
   *
   * @schema ImageUpdateAutomationV1Beta2SpecGitCommit#messageTemplate
   */
  readonly messageTemplate?: string;

  /**
   * SigningKey provides the option to sign commits with a GPG key
   *
   * @schema ImageUpdateAutomationV1Beta2SpecGitCommit#signingKey
   */
  readonly signingKey?: ImageUpdateAutomationV1Beta2SpecGitCommitSigningKey;

}

/**
 * Converts an object of type 'ImageUpdateAutomationV1Beta2SpecGitCommit' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_ImageUpdateAutomationV1Beta2SpecGitCommit(obj: ImageUpdateAutomationV1Beta2SpecGitCommit | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'author': toJson_ImageUpdateAutomationV1Beta2SpecGitCommitAuthor(obj.author),
    'messageTemplate': obj.messageTemplate,
    'signingKey': toJson_ImageUpdateAutomationV1Beta2SpecGitCommitSigningKey(obj.signingKey),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * Push specifies how and where to push commits made by the
 * automation. If missing, commits are pushed (back) to
 * `.spec.checkout.branch` or its default.
 *
 * @schema ImageUpdateAutomationV1Beta2SpecGitPush
 */
export interface ImageUpdateAutomationV1Beta2SpecGitPush {
  /**
   * Branch specifies that commits should be pushed to the branch
   * named. The branch is created using `.spec.checkout.branch` as the
   * starting point, if it doesn't already exist.
   *
   * @schema ImageUpdateAutomationV1Beta2SpecGitPush#branch
   */
  readonly branch?: string;

  /**
   * Options specifies the push options that are sent to the Git
   * server when performing a push operation. For details, see:
   * https://git-scm.com/docs/git-push#Documentation/git-push.txt---push-optionltoptiongt
   *
   * @schema ImageUpdateAutomationV1Beta2SpecGitPush#options
   */
  readonly options?: { [key: string]: string };

  /**
   * Refspec specifies the Git Refspec to use for a push operation.
   * If both Branch and Refspec are provided, then the commit is pushed
   * to the branch and also using the specified refspec.
   * For more details about Git Refspecs, see:
   * https://git-scm.com/book/en/v2/Git-Internals-The-Refspec
   *
   * @schema ImageUpdateAutomationV1Beta2SpecGitPush#refspec
   */
  readonly refspec?: string;

}

/**
 * Converts an object of type 'ImageUpdateAutomationV1Beta2SpecGitPush' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_ImageUpdateAutomationV1Beta2SpecGitPush(obj: ImageUpdateAutomationV1Beta2SpecGitPush | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'branch': obj.branch,
    'options': ((obj.options) === undefined) ? undefined : (Object.entries(obj.options).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {})),
    'refspec': obj.refspec,
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * A label selector requirement is a selector that contains values, a key, and an operator that
 * relates the key and values.
 *
 * @schema ImageUpdateAutomationV1Beta2SpecPolicySelectorMatchExpressions
 */
export interface ImageUpdateAutomationV1Beta2SpecPolicySelectorMatchExpressions {
  /**
   * key is the label key that the selector applies to.
   *
   * @schema ImageUpdateAutomationV1Beta2SpecPolicySelectorMatchExpressions#key
   */
  readonly key: string;

  /**
   * operator represents a key's relationship to a set of values.
   * Valid operators are In, NotIn, Exists and DoesNotExist.
   *
   * @schema ImageUpdateAutomationV1Beta2SpecPolicySelectorMatchExpressions#operator
   */
  readonly operator: string;

  /**
   * values is an array of string values. If the operator is In or NotIn,
   * the values array must be non-empty. If the operator is Exists or DoesNotExist,
   * the values array must be empty. This array is replaced during a strategic
   * merge patch.
   *
   * @schema ImageUpdateAutomationV1Beta2SpecPolicySelectorMatchExpressions#values
   */
  readonly values?: string[];

}

/**
 * Converts an object of type 'ImageUpdateAutomationV1Beta2SpecPolicySelectorMatchExpressions' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_ImageUpdateAutomationV1Beta2SpecPolicySelectorMatchExpressions(obj: ImageUpdateAutomationV1Beta2SpecPolicySelectorMatchExpressions | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'key': obj.key,
    'operator': obj.operator,
    'values': obj.values?.map(y => y),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * Kind of the referent.
 *
 * @schema ImageUpdateAutomationV1Beta2SpecSourceRefKind
 */
export enum ImageUpdateAutomationV1Beta2SpecSourceRefKind {
  /** GitRepository */
  GIT_REPOSITORY = "GitRepository",
}

/**
 * Strategy names the strategy to be used.
 *
 * @schema ImageUpdateAutomationV1Beta2SpecUpdateStrategy
 */
export enum ImageUpdateAutomationV1Beta2SpecUpdateStrategy {
  /** Setters */
  SETTERS = "Setters",
}

/**
 * Reference gives a branch, tag or commit to clone from the Git
 * repository.
 *
 * @schema ImageUpdateAutomationV1Beta2SpecGitCheckoutRef
 */
export interface ImageUpdateAutomationV1Beta2SpecGitCheckoutRef {
  /**
   * Branch to check out, defaults to 'master' if no other field is defined.
   *
   * @schema ImageUpdateAutomationV1Beta2SpecGitCheckoutRef#branch
   */
  readonly branch?: string;

  /**
   * Commit SHA to check out, takes precedence over all reference fields.
   *
   *
   * This can be combined with Branch to shallow clone the branch, in which
   * the commit is expected to exist.
   *
   * @schema ImageUpdateAutomationV1Beta2SpecGitCheckoutRef#commit
   */
  readonly commit?: string;

  /**
   * Name of the reference to check out; takes precedence over Branch, Tag and SemVer.
   *
   *
   * It must be a valid Git reference: https://git-scm.com/docs/git-check-ref-format#_description
   * Examples: "refs/heads/main", "refs/tags/v0.1.0", "refs/pull/420/head", "refs/merge-requests/1/head"
   *
   * @schema ImageUpdateAutomationV1Beta2SpecGitCheckoutRef#name
   */
  readonly name?: string;

  /**
   * SemVer tag expression to check out, takes precedence over Tag.
   *
   * @schema ImageUpdateAutomationV1Beta2SpecGitCheckoutRef#semver
   */
  readonly semver?: string;

  /**
   * Tag to check out, takes precedence over Branch.
   *
   * @schema ImageUpdateAutomationV1Beta2SpecGitCheckoutRef#tag
   */
  readonly tag?: string;

}

/**
 * Converts an object of type 'ImageUpdateAutomationV1Beta2SpecGitCheckoutRef' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_ImageUpdateAutomationV1Beta2SpecGitCheckoutRef(obj: ImageUpdateAutomationV1Beta2SpecGitCheckoutRef | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'branch': obj.branch,
    'commit': obj.commit,
    'name': obj.name,
    'semver': obj.semver,
    'tag': obj.tag,
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * Author gives the email and optionally the name to use as the
 * author of commits.
 *
 * @schema ImageUpdateAutomationV1Beta2SpecGitCommitAuthor
 */
export interface ImageUpdateAutomationV1Beta2SpecGitCommitAuthor {
  /**
   * Email gives the email to provide when making a commit.
   *
   * @schema ImageUpdateAutomationV1Beta2SpecGitCommitAuthor#email
   */
  readonly email: string;

  /**
   * Name gives the name to provide when making a commit.
   *
   * @schema ImageUpdateAutomationV1Beta2SpecGitCommitAuthor#name
   */
  readonly name?: string;

}

/**
 * Converts an object of type 'ImageUpdateAutomationV1Beta2SpecGitCommitAuthor' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_ImageUpdateAutomationV1Beta2SpecGitCommitAuthor(obj: ImageUpdateAutomationV1Beta2SpecGitCommitAuthor | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'email': obj.email,
    'name': obj.name,
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * SigningKey provides the option to sign commits with a GPG key
 *
 * @schema ImageUpdateAutomationV1Beta2SpecGitCommitSigningKey
 */
export interface ImageUpdateAutomationV1Beta2SpecGitCommitSigningKey {
  /**
   * SecretRef holds the name to a secret that contains a 'git.asc' key
   * corresponding to the ASCII Armored file containing the GPG signing
   * keypair as the value. It must be in the same namespace as the
   * ImageUpdateAutomation.
   *
   * @schema ImageUpdateAutomationV1Beta2SpecGitCommitSigningKey#secretRef
   */
  readonly secretRef?: ImageUpdateAutomationV1Beta2SpecGitCommitSigningKeySecretRef;

}

/**
 * Converts an object of type 'ImageUpdateAutomationV1Beta2SpecGitCommitSigningKey' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_ImageUpdateAutomationV1Beta2SpecGitCommitSigningKey(obj: ImageUpdateAutomationV1Beta2SpecGitCommitSigningKey | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'secretRef': toJson_ImageUpdateAutomationV1Beta2SpecGitCommitSigningKeySecretRef(obj.secretRef),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * SecretRef holds the name to a secret that contains a 'git.asc' key
 * corresponding to the ASCII Armored file containing the GPG signing
 * keypair as the value. It must be in the same namespace as the
 * ImageUpdateAutomation.
 *
 * @schema ImageUpdateAutomationV1Beta2SpecGitCommitSigningKeySecretRef
 */
export interface ImageUpdateAutomationV1Beta2SpecGitCommitSigningKeySecretRef {
  /**
   * Name of the referent.
   *
   * @schema ImageUpdateAutomationV1Beta2SpecGitCommitSigningKeySecretRef#name
   */
  readonly name: string;

}

/**
 * Converts an object of type 'ImageUpdateAutomationV1Beta2SpecGitCommitSigningKeySecretRef' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_ImageUpdateAutomationV1Beta2SpecGitCommitSigningKeySecretRef(obj: ImageUpdateAutomationV1Beta2SpecGitCommitSigningKeySecretRef | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'name': obj.name,
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

