{
 "title": "Downloader",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   { "name": "prom", "query": "prometheus" },
   {
    "name": "topic",
    "query": {
     "query": "label_values(kafka_log_log_logendoffset,topic)"
    }
   },
   {
    "name": "consumer_group",
    "query": {
     "query": "label_values(kafka_consumergroup_lag{topic=\"$topic\"},consumergroup)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Kafka", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Number of messages",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_log_log_logendoffset{topic=\"$topic\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Num of partitions",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 5, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(max by (partition) (kafka_log_log_size{topic=\"$topic\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Producement vs consument",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 15, "x": 9, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(kafka_log_log_logendoffset{topic=\"$topic\"}[$__rate_interval]))",
     "legendFormat": "producer"
    },
    {
     "expr": "sum(rate(image_downloader_messages_consumed_total{}[$__rate_interval])) * -1",
     "legendFormat": "consumer"
    }
   ]
  },
  {
   "title": "Size of job channel",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "image_downloader_job_channel_size",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Number of downloaders",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 6, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(image_downloader_workers_running)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Consumer lag",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 8 },
   "targets": [
    {
     "expr": "kafka_consumergroup_lag{topic=\"${topic}\", consumergroup=\"${consumer_group}\"}",
     "legendFormat": "{{partition}}"
    }
   ]
  },
  {
   "title": "Lag",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_consumergroup_lag{topic=\"${topic}\", consumergroup=\"${consumer_group}\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Image processing", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Image downloading",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 20, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "rate(image_downloader_images_downloaded_total[$__rate_interval])",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "rate(image_downloader_download_errors_total[$__rate_interval]) * -1",
     "legendFormat": "{{pod}}-fail"
    }
   ]
  },
  {
   "title": "Image download",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(image_downloader_images_downloaded_total[$__range]))",
     "legendFormat": "done"
    },
    {
     "expr": "sum(increase(image_downloader_download_errors_total[$__range]))",
     "legendFormat": "fail"
    }
   ]
  },
  {
   "title": "Image uploading",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 20, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "rate(image_downloader_images_uploaded_total[$__rate_interval])",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "rate(image_downloader_upload_errors_total[$__rate_interval]) * -1",
     "legendFormat": "{{pod}}-fail"
    }
   ]
  },
  {
   "title": "Image upload",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(image_downloader_images_uploaded_total[$__range]))",
     "legendFormat": "done"
    },
    {
     "expr": "sum(increase(image_downloader_upload_errors_total[$__range]))",
     "legendFormat": "fail"
    }
   ]
  },
  {
   "title": "Metadata extraction",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 20, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "rate(image_downloader_images_extracted_total[$__rate_interval])",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "rate(image_downloader_extraction_errors_total[$__rate_interval]) * -1",
     "legendFormat": "{{pod}}-fail"
    }
   ]
  },
  {
   "title": "Image upload",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(image_downloader_images_extracted_total[$__range]))",
     "legendFormat": "done"
    },
    {
     "expr": "sum(increase(image_downloader_extraction_errors_total[$__range]))",
     "legendFormat": "fail"
    }
   ]
  },
  { "title": "Image reactor", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "Metadata store",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "sum(rate(image_reactor_images_stored_total[$__rate_interval])) by (database_id) ",
     "legendFormat": "{{database_id}}"
    }
   ]
  },
  {
   "title": "Image uploaded",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 41 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(image_reactor_images_stored_total)",
     "legendFormat": "{{database_id}}"
    }
   ]
  },
  {
   "title": "Image upload per db",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 41 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(image_reactor_images_stored_total) by (database_id)",
     "legendFormat": "{{database_id}}"
    }
   ]
  },
  {
   "title": "Metadata failed attempts",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "sum(rate(image_reactor_failed_attempts_total[$__rate_interval])) by (database_id)  or vector(0)",
     "legendFormat": "{{database_id}}"
    }
   ]
  },
  {
   "title": "Failed attempts",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 48 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(image_reactor_failed_attempts_total) or vector(0)",
     "legendFormat": "{{database_id}}"
    }
   ]
  },
  {
   "title": "Failed attempts db",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 48 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(image_reactor_failed_attempts_total[$__range])) by (database_id) ",
     "legendFormat": "{{database_id}}"
    }
   ]
  }
 ]
}