source "https://rubygems.org"

gem "bolt",   "~> 4.0"
gem 'facter', "~> 4.0"

gem 'ed25519',      '~> 1.4'
gem 'bcrypt_pbkdf', '~> 1.1'
# Puppet lint and format
group :lint do
  gem 'puppet-lint',                            require: false
  gem 'puppet-lint-strict_indent-check',        require: false
  gem 'puppet-lint-manifest_whitespace-check',  require: false
  gem 'puppet-lint-unquoted_string-check',      require: false
  gem 'puppet-lint-leading_zero-check',         require: false
  gem 'puppet-lint-absolute_classname-check',   require: false
  gem 'puppet-lint-trailing_comma-check',       require: false
  gem 'puppet-lint-file_ensure-check',          require: false
  gem 'puppet-lint-legacy_facts-check',         require: false
  gem 'puppet-lint-class_alignment-check',      require: false
  gem 'puppet-lint-param-docs',                 require: false
end
